file:
  path: D:\fit\

baseUrl: http://localhost:8001/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fit?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
